// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: startport/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryArchievementsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryArchievementsRequest) Reset()         { *m = QueryArchievementsRequest{} }
func (m *QueryArchievementsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryArchievementsRequest) ProtoMessage()    {}
func (*QueryArchievementsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53c804e5859b9a4f, []int{0}
}
func (m *QueryArchievementsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryArchievementsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryArchievementsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryArchievementsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryArchievementsRequest.Merge(m, src)
}
func (m *QueryArchievementsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryArchievementsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryArchievementsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryArchievementsRequest proto.InternalMessageInfo

func (m *QueryArchievementsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryArchievementsResponse struct {
	Archievement []*Archievement     `protobuf:"bytes,1,rep,name=Archievement,proto3" json:"Archievement,omitempty"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryArchievementsResponse) Reset()         { *m = QueryArchievementsResponse{} }
func (m *QueryArchievementsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryArchievementsResponse) ProtoMessage()    {}
func (*QueryArchievementsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53c804e5859b9a4f, []int{1}
}
func (m *QueryArchievementsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryArchievementsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryArchievementsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryArchievementsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryArchievementsResponse.Merge(m, src)
}
func (m *QueryArchievementsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryArchievementsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryArchievementsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryArchievementsResponse proto.InternalMessageInfo

func (m *QueryArchievementsResponse) GetArchievement() []*Archievement {
	if m != nil {
		return m.Archievement
	}
	return nil
}

func (m *QueryArchievementsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryArchievementRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryArchievementRequest) Reset()         { *m = QueryArchievementRequest{} }
func (m *QueryArchievementRequest) String() string { return proto.CompactTextString(m) }
func (*QueryArchievementRequest) ProtoMessage()    {}
func (*QueryArchievementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53c804e5859b9a4f, []int{2}
}
func (m *QueryArchievementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryArchievementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryArchievementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryArchievementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryArchievementRequest.Merge(m, src)
}
func (m *QueryArchievementRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryArchievementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryArchievementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryArchievementRequest proto.InternalMessageInfo

func (m *QueryArchievementRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryArchievementResponse struct {
	Archievement *Archievement `protobuf:"bytes,1,opt,name=Archievement,proto3" json:"Archievement,omitempty"`
}

func (m *QueryArchievementResponse) Reset()         { *m = QueryArchievementResponse{} }
func (m *QueryArchievementResponse) String() string { return proto.CompactTextString(m) }
func (*QueryArchievementResponse) ProtoMessage()    {}
func (*QueryArchievementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53c804e5859b9a4f, []int{3}
}
func (m *QueryArchievementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryArchievementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryArchievementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryArchievementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryArchievementResponse.Merge(m, src)
}
func (m *QueryArchievementResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryArchievementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryArchievementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryArchievementResponse proto.InternalMessageInfo

func (m *QueryArchievementResponse) GetArchievement() *Archievement {
	if m != nil {
		return m.Archievement
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryArchievementsRequest)(nil), "DangVTNhan.startport.startport.QueryArchievementsRequest")
	proto.RegisterType((*QueryArchievementsResponse)(nil), "DangVTNhan.startport.startport.QueryArchievementsResponse")
	proto.RegisterType((*QueryArchievementRequest)(nil), "DangVTNhan.startport.startport.QueryArchievementRequest")
	proto.RegisterType((*QueryArchievementResponse)(nil), "DangVTNhan.startport.startport.QueryArchievementResponse")
}

func init() { proto.RegisterFile("startport/query.proto", fileDescriptor_53c804e5859b9a4f) }

var fileDescriptor_53c804e5859b9a4f = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4f, 0x8b, 0xd3, 0x40,
	0x14, 0xef, 0xa4, 0x28, 0x38, 0x55, 0x0f, 0x03, 0x42, 0x0d, 0x25, 0x94, 0x1c, 0xb4, 0x94, 0x32,
	0x43, 0x5a, 0x0f, 0xd6, 0x9b, 0x22, 0x7a, 0x10, 0xa4, 0x06, 0xf1, 0xe0, 0x6d, 0x92, 0x0e, 0xe9,
	0x80, 0x99, 0x49, 0x33, 0xd3, 0x62, 0x11, 0x2f, 0x5e, 0xbc, 0x0a, 0x7e, 0x18, 0x2f, 0xb2, 0xe7,
	0x3d, 0x16, 0xf6, 0xb2, 0xc7, 0xa5, 0xdd, 0x0f, 0xb2, 0x34, 0x49, 0x37, 0x09, 0x9b, 0x6d, 0x69,
	0xf7, 0x36, 0xf0, 0xde, 0xef, 0xdf, 0xe3, 0x37, 0xf0, 0x89, 0xd2, 0x34, 0xd6, 0x91, 0x8c, 0x35,
	0x99, 0xce, 0x58, 0xbc, 0xc0, 0x51, 0x2c, 0xb5, 0x44, 0xd6, 0x5b, 0x2a, 0x82, 0x2f, 0x9f, 0x3f,
	0x4e, 0xa8, 0xc0, 0xd7, 0x1b, 0xf9, 0xcb, 0x6c, 0x05, 0x52, 0x06, 0xdf, 0x18, 0xa1, 0x11, 0x27,
	0x54, 0x08, 0xa9, 0xa9, 0xe6, 0x52, 0xa8, 0x14, 0x6d, 0x76, 0x7d, 0xa9, 0x42, 0xa9, 0x88, 0x47,
	0x15, 0x4b, 0x69, 0xc9, 0xdc, 0xf1, 0x98, 0xa6, 0x0e, 0x89, 0x68, 0xc0, 0x45, 0xb2, 0x9c, 0xed,
	0xb6, 0x72, 0x03, 0x34, 0xf6, 0x27, 0x9c, 0xcd, 0x59, 0xc8, 0x84, 0x4e, 0xa7, 0xb6, 0x0f, 0x9f,
	0x7e, 0xda, 0xe0, 0x5f, 0x17, 0x46, 0xca, 0x65, 0xd3, 0x19, 0x53, 0x1a, 0xbd, 0x83, 0x30, 0xa7,
	0x6b, 0x82, 0x36, 0xe8, 0x34, 0xfa, 0xcf, 0x70, 0xaa, 0x8d, 0x37, 0xda, 0x38, 0x8d, 0x94, 0x69,
	0xe3, 0x11, 0x0d, 0x58, 0x86, 0x75, 0x0b, 0x48, 0xfb, 0x1f, 0x80, 0x66, 0x95, 0x8a, 0x8a, 0xa4,
	0x50, 0x0c, 0x8d, 0xe0, 0xc3, 0xe2, 0xa0, 0x09, 0xda, 0xf5, 0x4e, 0xa3, 0xdf, 0xc3, 0xbb, 0x4f,
	0x84, 0x8b, 0x18, 0xb7, 0xc4, 0x80, 0xde, 0x97, 0x8c, 0x1b, 0x89, 0xf1, 0xe7, 0x7b, 0x8d, 0xa7,
	0x76, 0x4a, 0xce, 0xbb, 0xb0, 0x79, 0xc3, 0xf8, 0xf6, 0x3a, 0x8f, 0xa1, 0xc1, 0xc7, 0xc9, 0x55,
	0x1e, 0xb8, 0x06, 0x1f, 0xdb, 0x61, 0xc5, 0x29, 0x77, 0x64, 0x04, 0x77, 0xcb, 0xd8, 0xff, 0x5d,
	0x87, 0xf7, 0x12, 0x3d, 0x74, 0x02, 0xca, 0xe4, 0xe8, 0xe5, 0x3e, 0xda, 0xdb, 0x32, 0x99, 0xc3,
	0x23, 0x90, 0x69, 0x42, 0x7b, 0xf8, 0xeb, 0xec, 0xf2, 0xaf, 0x31, 0x40, 0x0e, 0xc9, 0x29, 0x48,
	0xde, 0xbd, 0xea, 0x16, 0x92, 0x1f, 0x7c, 0xfc, 0x13, 0xfd, 0x07, 0xf0, 0x51, 0xa9, 0x1a, 0xe8,
	0x70, 0x1f, 0xdb, 0xd2, 0x9a, 0xaf, 0x8e, 0x81, 0x66, 0x19, 0x5e, 0x24, 0x19, 0x30, 0xea, 0x1d,
	0x92, 0xe1, 0xcd, 0x87, 0xd3, 0x95, 0x05, 0x96, 0x2b, 0x0b, 0x5c, 0xac, 0x2c, 0xf0, 0x67, 0x6d,
	0xd5, 0x96, 0x6b, 0xab, 0x76, 0xbe, 0xb6, 0x6a, 0x5f, 0x9d, 0x80, 0xeb, 0xc9, 0xcc, 0xc3, 0xbe,
	0x0c, 0xab, 0x19, 0xbf, 0x17, 0xde, 0x7a, 0x11, 0x31, 0xe5, 0xdd, 0x4f, 0xfe, 0xe5, 0xe0, 0x2a,
	0x00, 0x00, 0xff, 0xff, 0x2a, 0xce, 0x76, 0xec, 0x38, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	Archievement(ctx context.Context, in *QueryArchievementRequest, opts ...grpc.CallOption) (*QueryArchievementResponse, error)
	// Queries a list of archievements items.
	Archievements(ctx context.Context, in *QueryArchievementsRequest, opts ...grpc.CallOption) (*QueryArchievementsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Archievement(ctx context.Context, in *QueryArchievementRequest, opts ...grpc.CallOption) (*QueryArchievementResponse, error) {
	out := new(QueryArchievementResponse)
	err := c.cc.Invoke(ctx, "/DangVTNhan.startport.startport.Query/Archievement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Archievements(ctx context.Context, in *QueryArchievementsRequest, opts ...grpc.CallOption) (*QueryArchievementsResponse, error) {
	out := new(QueryArchievementsResponse)
	err := c.cc.Invoke(ctx, "/DangVTNhan.startport.startport.Query/Archievements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	Archievement(context.Context, *QueryArchievementRequest) (*QueryArchievementResponse, error)
	// Queries a list of archievements items.
	Archievements(context.Context, *QueryArchievementsRequest) (*QueryArchievementsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Archievement(ctx context.Context, req *QueryArchievementRequest) (*QueryArchievementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Archievement not implemented")
}
func (*UnimplementedQueryServer) Archievements(ctx context.Context, req *QueryArchievementsRequest) (*QueryArchievementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Archievements not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Archievement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryArchievementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Archievement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DangVTNhan.startport.startport.Query/Archievement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Archievement(ctx, req.(*QueryArchievementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Archievements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryArchievementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Archievements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DangVTNhan.startport.startport.Query/Archievements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Archievements(ctx, req.(*QueryArchievementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DangVTNhan.startport.startport.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Archievement",
			Handler:    _Query_Archievement_Handler,
		},
		{
			MethodName: "Archievements",
			Handler:    _Query_Archievements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "startport/query.proto",
}

func (m *QueryArchievementsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryArchievementsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryArchievementsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryArchievementsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryArchievementsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryArchievementsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Archievement) > 0 {
		for iNdEx := len(m.Archievement) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Archievement[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryArchievementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryArchievementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryArchievementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryArchievementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryArchievementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryArchievementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Archievement != nil {
		{
			size, err := m.Archievement.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryArchievementsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryArchievementsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Archievement) > 0 {
		for _, e := range m.Archievement {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryArchievementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryArchievementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Archievement != nil {
		l = m.Archievement.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryArchievementsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryArchievementsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryArchievementsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryArchievementsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryArchievementsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryArchievementsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archievement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Archievement = append(m.Archievement, &Archievement{})
			if err := m.Archievement[len(m.Archievement)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryArchievementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryArchievementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryArchievementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryArchievementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryArchievementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryArchievementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archievement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Archievement == nil {
				m.Archievement = &Archievement{}
			}
			if err := m.Archievement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
